bert:
  language: de
  type_sentences: toklem
  layers: 1+12
  is_len: False
  path_output1: ../output/vectors_bert_corpus1/
  path_output2: ../output/vectors_bert_corpus2/
  path_results: ../results/
  path_targets: ../targets/
